const categoryOptions = [
  'Accounting',
  'Account Management',
  'Administration and Office',
  'Advertising and Marketing',
  'Animal Care',
  'Arts',
  'Business Operations',
  'Computer and IT',
  'Construction',
  'Corporate',
  'Customer Service',
  'Data and Analytics',
  'Data Science',
  'Design',
  'Development',
  'Editing',
  'Education',
  'Entertainment and Travel Services',
  'Farming and Outdoors',
  'Food and Hospitality Services',
  'Healthcare',
  'Human Resources and Recruitment',
  'Installation, Maintenance, and Repairs',
  'IT',
  'Legal Services',
  'Management',
  'Manufacturing and Warehouse',
  'Marketing',
  'Media, PR, and Communications',
  'Mental Health',
  'Office Administration',
  'Personal Care and Services',
  'Product Management',
  'Project Management',
  'Public Relations',
  'Real Estate',
  'Recruiting',
  'Retail',
  'Sales',
  'Science and Engineering',
  'Social Services',
  'Sports, Fitness, and Recreation',
  'Telemarketing',
  'Transportation and Logistics',
  'UI/UX Design',
  'Videography',
  'Web Design',
  'Writing and Editing',
  'Software Engineering',
  'Software Developement',
  'Web Developement',
  'Artificial Intelligence (A.I.)',
];

categoryOptions.sort((a, b) => a.localeCompare(b));

export default categoryOptions;
